services.service("dkwDataMonitor", ['dkwData', '$filter',function DemoInfo(dkwData, $filter){
  return {
    all: function(){
      var siteData = {"solutions":dkwData.dkwSolutions, "ourCompany":dkwData.ourCompany, "news": dkwData.dkwNews, "contractVehicles":dkwData.dkwContractVehicles};
      return siteData;
    },
    pages:{
      solutions: function(title){
        var solutionsPage = null;
        if(title != null){
          var regex = /\s/g;
          var searchTitle = title.replace(regex, "|");
          solutionsPage = dkwData.dkwSolutions[searchTitle];
        }
        return solutionsPage;
      },
      ourCompany: function(title) {
        var ourCompanyPage = null;
        if(title != null){
          var regex = /\s/g;
          var searchTitle = title.replace(regex, "|");
          ourCompanyPage = dkwData.ourCompany[searchTitle];
        }
        return ourCompanyPage;
        
      }
    },
    search: {
      all:function(){
        var solutions = dkwData.dkwSolutions;
        var solutionsArray = [];
        for(var key in solutions){
          solutionsArray.push(solutions[key]);
        }

        var siteData = {"solutions":solutionsArray, "news": dkwData.dkwNews,"contractVehicles":dkwData.dkwContractVehicles};
        return siteData;
      }
    }
  }
}])
.factory("dkwData", ['$http', function ($http){
  function dkwInfoData() {
    var data = this;

    // Solutions Data
    data.dkwSolutions = {
        "Enterprise|Net-Centric|Solutions":{"sectionTitle":"Enterprise Net-Centric Solutions", "image":"images/teamwork.jpg", "icon":"fa-home", "state":'app.solutions.netCentricSolutions({Id:""})',
        "content":[
          {"type":"text", "content":"DKW designs, engineers, deploys, and maintains a full range of software, database, and web information systems through a structured, disciplined set of proven systems and application software engineering practices and life cycle maintenance techniques. These practices encompass the full life cycle development process from project analysis to project closeout for projects requiring the development or modification of systems and software. Our approach to defining the systems and software engineering practices is based on the Software Engineering Institute’s (SEI) Capability Maturity Model Integration (CMMI) Level 2 best practices, which have been assessed at Capability Maturity Model Integration (CMMI) Level 3."},
          {"type":"list", "content":["Since 2006, DKW has supported SPAWAR Atlantic in the application of sound software development, software engineering, and programming support, based our end-customers’ System Development Lifecycle (SDLC). Our team of software architects, engineers, developers, quality assurance testers, and technical writers have applied engineering, security, and scientific disciplines for a variety of financial management, medical, administrative, and logistics management applications, developing these applications using the classic waterfall or Agile development approach as best fit the client’s requirements.","DKW has been a significant contributor to the transformation of the Public Health Information System (PHIS), a critical USDA system used to protect our Nation’s food sources. This complex system consists of 800 database tables and 5.8 million lines of code."]},
          {"type":"text", "spacer":true, "content":"Since 2010, DKW has been providing CMMI DEV L3-appraised Information Technology Services (ITS) and Software Maintenance Support (SMS) for the PHIS application, which is a comprehensive, data-driven inspection system comprised of multiple applications that was developed to collect, mine and analyze inspection, surveillance and investigative data; predict hazards and vulnerabilities; communicate or report analysis results; and target resources to prevent or mitigate the risk of food borne illness and threats to the nation’s food supply. DKW has been the key enabler for USDA in implementing required enhancements to FSIS through waterfall, agile, and hybrid software development methodologies, and we have transitioned 11 USDA legacy systems in the process."},
          {"type":"text","content":"DKW has worked closely with FSIS as it implemented a phased approach to the continual development and maintenance of PHIS to ensure that FSIS employees and other users of PHIS could accomplish their primary objectives without interruption of business operations. This phased approach sought to stabilize, optimize, and then transform PHIS."},
          {"type":"list","content":["DKW is prime contractor in support of the Global Information Grid (GIG) Technical Guidance Federation (GTG-F), which is a suite of software applications on the NIPRNet and SIPRNet that provide technical guidance across the DISA Enterprise to achieve net-ready, interoperable, and supportable GIG systems. The GTG-F assists program managers, portfolio managers, engineers, and others in answering two questions critical to any IT or National Security Systems (NSS): (1) Where does the IT or NSS fit, as both a provider and consumer, into the GIG with regard to End-to-End technical performance, access to data and services, and interoperability?; and (2) What must an IT system or NSS do to ensure technical interoperability with the GIG? Several of the GIG Technical Guidance business processes have joined together as a single Web destination that has provided several advantages to our clients, such as ease of use, reduced hosting costs, and increasing data availability to the DoD community. DKW architects, designs, develops, implements, and provides maintenance for the GTG Federated Tools Suite. It is the authoritative source for ISP assessment data, GTPs with implementation guidance, and compliance. The GTG Federated Tools Suite program is a key enabler of the ongoing DISA-led IT enterprise transformation.","DKW modernized the Navy Fleet’s Sensitive Compartmented Information (SCI) Network Operations Center (NOC), which was formerly an antiquated network with an overly complex footprint that was difficult to manage. DKW analyzed the system architecture, the CONOPS, and the security environment to identify which areas needed to be improved and which vulnerabilities needed to be addressed. DKW discovered that the hardware and software were in some cases at end-of-life, a situation which the Navy deemed an unacceptable level of risk."]},
          {"type":"text","content":"DKW provided the Fleet SCI NOC with solutions that mitigated the risks, including replacement of older Cisco routers and Catalyst switches with upgraded components, reducing the overall footprint and complexity and increasing overall efficiency as well as virtualizing the hardware using VMware."}
        ],
        "items":[
          {"title":"Application Development", "state":'app.solutions.netCentricSolutions({Id: "application-development" })', "image":"images/appdev2.jpg", "icon":"fa-desktop", "content":[{"type":"text", "content":"DKW’s Application Development service offerings provide application consulting, custom application development, testing, and quality assurance. We develop high quality business applications that increase operational efficiency and sustain your competitive advantage. DKW’s Applications Development allow your organization to take advantage of emerging technologies while offering a substantial reduction in capital expenditure, improved responsiveness to business demands, increased agility, and a faster time to market. We combine deep industry experience, highly skilled resources, and proven processes to deliver software solutions that fully support your goals. In addition, DKW’s cloud-based development platform allows us to develop and deliver applications across a multitude of platforms and technologies." }]},
          {"title":"C5ISR", "state":'app.solutions.netCentricSolutions({Id: "c5isr" })',"image":"images/c5sir1.jpg", "icon":"fa-rocket", "content":[{"type":"text", "content":"DKW’s C5ISR professionals have experience in the design, installation, configuration, testing, and/or going support of a wide range of systems, such as: Messaging & Communications Systems, Tactical Systems, Enterprise IT Infrastructure, Cyber Defense Systems, and Intelligence Systems. DKW is capable of supporting virtually any C5ISR support requirement, from the Enterprise-level engineering to end-user desktop support, both on GENSER and SCI platforms. Our mission-focused team is experienced in working around operational, technical, and administrative challenges to deliver our customers exceptional support. DKW’s services are highly customized to meet the unique needs and expectations of our customers." }]},
          {"title":"Datacenter Support", "state":'app.solutions.netCentricSolutions({Id: "datacenter-support" })',"image":"images/datacenter1.jpg", "icon":"fa-database", "content":[{"type":"text", "content":"DKW delivers scalable, reliable, and secure Data Center Support solutions to help maximize your existing technology investments and better meet your current and future technology needs. DKW offers some of the most reliable and affordable data center services in the industry. Our experienced staff of certified engineers are available at all hours of the day or night to provide the data center services you need to keep your business running. Our data centers offer various options for power, space, managed IT and hosting, virtual solutions, and cloud solutions. With years of experience managing, maintaining, and operating data center facilities, you can be assured that your critical data assets are secure and available." }]},
          {"title":"Healthcare IT", "state":'app.solutions.netCentricSolutions({Id: "healthcare-it" })',"image":"images/healthIT1.jpg", "icon":"fa-medkit", "content":[{"type":"text", "content":"DKW delivers a wide range of Healthcare IT solutions—from addressing back office functions and electronic medical records to clinical transformation and consumer engagement. DKW can assess your readiness from a technological perspective, build a Healthcare IT solutions roadmap, and bring your systems up to standard to support HIPAA requirements for patient data protection and support. Our commitment to value begins at architecture and extends to installation, monitoring, and maintenance. At DKW, we employ our cross-industry experts to bring the IT expertise in areas such as server consolidation, virtualization, remote access, high availability services, effective data communications architecture, wireless deployments, centralized vendor management, and proactive systems monitoring and management to healthcare. <br> Your medical practice can benefit from partnering with DKW for your technology support needs. We can help you make sense of technology and manage it efficiently and effectively so you can focus on your primary concern: patient care."}]},
          {"title":"IT Service Management", "state":'app.solutions.netCentricSolutions({Id: "it-service-management" })',"image":"images/itman2.jpg", "icon":"fa-server", "content":[{"type":"text", "content":"DKW’s IT Service Management solutions enable you to implement repeatable, measurable processes for defining, transitioning, delivering, and supporting services and assets throughout their life cycles. By integrating and automating Information Technology Infrastructure Library (ITIL) processes, you can utilize resources and control changes more efficiently, while streamlining the workload for your IT staff. With our comprehensive management capabilities, we can improve the quality of your services, prevent interruptions, and lower costs—all of which helps to ensure that your services stay aligned with your business requirements." }]},
          {"title":"IV&V", "state":'app.solutions.netCentricSolutions({Id: "iv&v" })',"image":"images/ivv2.png", "icon":"fa-check-square-o", "content":[{"type":"text", "content":"DKW’s Independent Verification and Validation (IV&V) processes provide an objective assessment of software products and processes throughout the software life cycle in an environment organizationally free from the influence, guidance, and control of the development effort. Our IV&V methodology is consistent with the latest systems engineering and process improvement models, and it has been assessed by the Capability Maturity Model Integration (CMMI)." }]},
          {"title":"Mobile Solutions", "state":'app.solutions.netCentricSolutions({Id: "mobile-solutions" })',"image":"images/mobilesolutions1.jpg", "icon":"fa-mobile", "content":[{"type":"text", "content":"DKW is a global provider of mobile solutions software for businesses of all sizes. By using our industry-leading experience, we develop easy-to-use, feature-rich mobile applications that extend the reach of your organization and employees. Our mobile experts are well equipped to help you extend existing technology solutions or develop new investments in cloud infrastructure to increase connectivity, collaboration, and productivity across your entire business." }]},
          {"title":"Operations and Maintenance", "state":'app.solutions.netCentricSolutions({Id: "operations-and-maintenance" })',"image":"images/itmain1.jpg", "icon":"fa-wrench", "content":[{"type":"text", "content":"DKW provides a broad range of IT operations support and maintenance services for a number of Federal civilian and DoD customers; we assist over 20,000 users located across the U.S. and around the world. The expansion, diversity, and increased sophistication of technology combined with our customers’ broad multi-site install-base requires that DKW be able to provide integrated service support and service delivery in all areas of communications, problem resolution, configuration management, and hardware and software operations and maintenance." }]},
          {"title":"Service Desk", "state":'app.solutions.netCentricSolutions({Id: "service-desk" })',"image":"images/serviceDesk1.jpg", "icon":"fa-handshake-o", "content":[{"type":"text", "content":"DKW’s Service Desk operations are delivered through a consistent set of tools and processes, using an ITIL based approach to IT Service Delivery. DKW has diverse experience in transitioning customers from multiple Helpdesks to a centralized Service Desk, which also leads to standardization across enterprise operations." }]},
          {"title":"Systems Engineering", "state":'app.solutions.netCentricSolutions({Id: "systems-engineering" })',"image":"images/systemseng1.jpg", "icon":"fa-code", "content":[{"type":"text", "content":"DKW’s proven ability to deliver quality products, while also meeting budget and schedule requirements is what makes us the premier service provider in the industry. DKW’s comprehensive and accurate requirements management process ensures that systems with well-designed hardware and software features meet exactly what users want and need. Our experience is essential as we work closely with clients, partners, and end-users to clearly define user needs and system requirements, and we deliver value at each step in the process. DKW’s systems engineers integrate all engineering disciplines into an efficient, streamlined process that smoothly takes the project from concept to production to operation, in order to meet our customer’s business and technical goals." }]},
          {"title":"Disability Accommodations", "state":'app.solutions.netCentricSolutions({Id: "disability-accommodations" })',"image":"images/disability1.jpg", "icon":"fa-wheelchair-alt", "content":[{"type":"text", "content":"DKW is committed to providing equal employment opportunity to all job seekers. If you are an individual with a disability who is unable to use our online tools to search and or apply for jobs, please send an email to disability-accommodations@199.230.117.121/dkwcomm and indicate the specifics of the assistance you need, or please contact the Disability Accommodations Office at 202-355-7400. This option is reserved only for individuals who are unable to use the online tools due to a disability or medical issue. It is not intended for other purposes or inquiries."}]}
        ]},
        "Cyber|Security|and|Intelligence|Service":{"sectionTitle":"Cyber Security and Intelligence Service", "image":"images/cybersecurity.jpg", "icon":"fa-home", "state":'app.solutions.cyberSecurityAndIntelligence({Id:""})',
          "content":[
            {"type":"subtitle2", "content":"At a Glance"},
            {"type":"list", "content":["Network-based malware detection for national organizations and cyber-security operation centers (CSOCs)", "Protects against advanced, unknown malware by going beyond signature-based intrusion detection mechanisms","High-end cyber security services that include training, consulting, and intelligence services","Cyber security experts with extensive background in management of CSOCs and training government organizations"]},

            {"type":"subtitle2", "content":"The Evolving Cyber Threat Landscape"},
            {"type":"text", "content":"A secure electronic communications infrastructure is vital to a nation’s security, stability, and economy. However, the growing frequency and sophistication of cyber attacks present significant challenges to nations worldwide. Among the thousands of cyber attacks occurring daily, the most severe threats are often the silent, multi-staged intrusions that are performed by determined and well-funded adversaries who are going after carefully chosen, high-profile targets. Many of these threats siphon confidential and sensitive information out of highly protected networks and ultimately undermine national security."},

            {"type":"subtitle2", "content":"DKW’s Cyber Security Solutions"},
            {"type":"text", "content":"DKW’s Cyber Security Solutions are designed to assist national level organizations and cyber security operation centers (CSOCs) in detecting and thwarting cyber attacks. Our portfolio includes DKW’s Network Security Solutions and additional secure Services."},
            {"type":"text", "content":"DKW’s Network Security Solutions feature a rich product portfolio designed to help national organizations and CSOCs detect and thwart cyber attacks."},
            {"type":"text", "content":"DKW’s flagship solution is our Advanced Detection System (ADS), which provides superior malware detection of signature-less threats by leveraging innovative, machine learning, and behavioral algorithms."},
            {"type":"text", "content":"DKW’s Services include training, consulting, intelligence, forensic investigations, and on-site cyber emergency services."},

            {"type":"subtitle2", "content":"Our Team"},
            {"type":"text", "content":"DKW’s team is powered by cyber security professionals with decades of experience across the cyber domain. Our world-class Cyber Security team was strategically built with the best individuals in the cyber arena today that have hands-on experience building the architectures and infrastructures necessary to secure large, high-risk networks."},
            {"type":"text", "content":"With vast prior experience in the formation of CSOCs for national organizations, our team is well acquainted with complex requirements and the formulation of cyber-defense strategies, policies, and standards."},

            {"type":"subtitle2", "content":"Securing National Assets from Cyber Attacks"},
            {"type":"text", "content":"The growing frequency and sophistication of cyber attacks present significant challenges to nations worldwide. DKW’s portfolio is designed to help government, military, and law enforcement agencies protect critical national assets from these increasingly persistent cyber threats. Our portfolio features an array of Network Security, as well as additional secure Services."},

            {"type":"subtitle2", "content":"DKW’s Network Security"},
            {"type":"text", "content":"DKW’s Network Security portfolio provides superior malware detection capabilities for high-speed networks, including national backbones, and it is built on over a decade of DKW’s experience with implementing large network monitoring projects for government organizations worldwide."},
            {"type":"text", "content":"DKW’s flagship solution, Advanced Detection System (ADS), provides superior malware detection of signature-less threats by leveraging innovative, machine learning, behavioral algorithms. By automatically sorting through tens of thousands of network sessions, this innovative cyber security solution identifies the command-and-control (C&C) channels of Advanced Persistent Threats (APTs) and provides the actionable intelligence needed to investigate and contain these threats."},

            {"type":"subtitle2", "content":"DKW’s Services"},
            {"type":"text", "content":"DKW’s Cyber Security Consulting Services, offer expert assistance for:"},
            {"type":"list", "content":["Designing a cyber security architecture for national assets","Establishing cyber security operations centers (CSOCs)","Evaluating potential cyber threats and relevant mitigation strategies","Developing strategic national cyber security policies, procedures, and organizational structures"]},
            {"type":"text", "content":"DKW’s cyber security training services feature a broad range of tailored training sessions for cyber incident responders, analysts, forensics experts, and other cyber professionals, as well as a national cyber strategy overview seminar for executives."},
            {"type":"text", "content":"DKW’s on-site cyber emergency services help organizations contain and mitigate cyber attacks in progress. These services include expert cyber forensic analysis of high-profile attacks, such as Advanced Persistent Threats (APTs), malware source code analysis, malware behavioral analysis, digital forensics, and network forensics."},
            {"type":"text", "content":"DKW’s cyber intelligence services help organizations develop a holistic cyber intelligence picture from a range of sources, including cyber threat-related Web content, Web platforms, and more. This intelligence helps organizations understand the motives and capabilities of potential cyber adversaries."},

            {"type":"subtitle1", "content":"DKW’s Advanced Detection System (ADS)"},
            {"type":"text", "content":"Last line of defense for your critical assets"},

            {"type":"subtitle2", "content":"At a Glance"},
            {"type":"list", "content":["Identify advanced, unknown malware","Go beyond signature-based intrusion detection","Detect threats hiding in the network","Leverage nonintrusive, network-based security","Overcome malicious traffic crafting and encryption"]},
            {"type":"text", "content":"DKW’s Advanced Detection System (ADS) is a scalable, high-performance network-security solution that provides superior malware detection for national organizations and cyber security operation centers (CSOCs) worldwide."},

            {"type":"subtitle2", "content":"Network Security for Targeted Cyber Attacks"},
            {"type":"text", "content":"DKW’s ADS is a behavioral-analysis platform for detecting advanced, unknown malware through the real-time analysis of network traffic. By automatically sorting through tens of thousands of network sessions, this innovative cyber security solution identifies the command-and-control (C&C) channels of Advanced Persistent Threats (APTs) and provides the actionable intelligence needed to investigate and contain these threats. By leveraging advanced machine-learning algorithms and behavioral-analysis methodologies, our ADS platform identifies new threats that have no recorded signatures or patterns and therefore cannot be detected by most cyber security mechanisms."},

            {"type":"subtitle2", "content":"Attacking the Achilles’ Heel of Malware"},
            {"type":"text", "content":"DKW’s ADS takes advantage of the main Achilles’ heel of any APT: its C&C channels. The system monitors volumes of ingress and egress traffic and constantly extracts hundreds of indicators describing IP communication flows. Subsequently, machine-learning algorithms are applied to the indicators to separate the advanced malware from the general traffic and to group the instances of malware into families. DKW’s ADS carries out these processes continuously on all network traffic and compares the indicators with those of malware behavioral profiles, which is generated from the combined intelligence gathered from thousands of known malware families."},

            {"type":"subtitle1", "content":"DKW’s Cyber Consulting Services"},
            {"type":"text", "content":"For defending national assets from cyber threats"},

            {"type":"subtitle2", "content":"At a Glance"},
            {"type":"text", "content":"World-class cyber security consulting services for:"},
            {"type":"list", "content":["Designing the cyber security architecture for national assets","Establishing cyber security operations centers (CSOCs)","Evaluating potential cyber-threats and relevant mitigation strategies","Developing strategic national cyber security policies, procedures, and organizational structures","Delivered by a committed team of technologists and cyber security experts with years of experience in the cyber domain"]},

            {"type":"subtitle2", "content":"Professional Cyber Security Consulting Services"},
            {"type":"text", "content":"The growing frequency and sophistication of cyber-attacks present significant challenges to nations worldwide. DKW has established Cyber Security Consulting Services that are designed to help organizations defend national assets against cyber-attack. Our broad Consulting Services portfolio covers:"},
            {"type":"text", "content":"Cyber Security Architecture for Critical Assets. Our consultants review your security infrastructure and help you develop a safe, resilient, and sustainable cyberspace for your critical assets."},
            {"type":"text", "content":"Establish Cyber Security Operations Centers (CSOCs). We help you develop the operational, technical, and methodological foundations for establishing situational awareness, real-time threat analysis, incident response, and cyber intelligence research."},
            {"type":"text", "content":"Cyber Threat Assessment. We provide expert evaluation of potential cyber attack scenarios and mitigation strategies. This assessment includes a top-down review, from strategy and business processes to IT and security infrastructures."},
            {"type":"text", "content":"Cyber Capacity Building. We help you develop strategic national cyber security policies, procedures, and organizational structures to help safeguard vital assets and information systems."}
          ],
          "items":[
            {"title":"Compliance and C&A", "state":'app.solutions.cyberSecurityAndIntelligence({Id: "compliance-and-ca" })',"image":"images/serviceDesk1.jpg", "icon":"fa-cubes", "content":[{"type":"text", "content":""}]},
            {"title":"COOP/Disaster Recovery", "state":'app.solutions.cyberSecurityAndIntelligence({Id: "coopdisaster-recovery" })',"image":"images/serviceDesk1.jpg", "icon":"fa-fire-extinguisher", "content":[{"type":"text", "content":""}]},
            {"title":"Identity Access Management", "state":'app.solutions.cyberSecurityAndIntelligence({Id: "identity-access-management" })',"image":"images/serviceDesk1.jpg", "icon":"fa-id-card-o", "content":[{"type":"text", "content":""}]},
            {"title":"Information Assurance", "state":'app.solutions.cyberSecurityAndIntelligence({Id: "information-assurance" })',"image":"images/serviceDesk1.jpg", "icon":"fa-info", "content":[{"type":"text", "content":""}]}
          ]
        },
        "Management|Consulting":{"sectionTitle":"Management Consulting", "image":"images/management.jpg", "icon":"fa-home", "state":'app.solutions.managementConsulting({Id:""})',
          "content":[
            {"type":"text", "content":"Your mission success is our priority. For more than a decade, our customers have relied on DKW’s professional and quick response capabilities."},
            {"type":"text", "content":"Whether analyzing and reengineering current business processes or assisting you in meeting ever-changing regulations and standards, DKW partners with you to ensure mission success."}
          ],
          "items":[
            {"title":"Acquisition Support", "state":'app.solutions.managementConsulting({Id: "acquisition-support" })',"image":"images/serviceDesk1.jpg", "icon":"fa-puzzle-piece", "content":[{"type":"text", "content":"The Federal procurement process is undergoing a major overhaul. We now must master new methods, rules, and requirements. The streamlined acquisition process adopts the best practices of the business world to boost cost-efficiency and reduce the time from contract development to delivery. Today’s acquisition management involves several major elements:"}, {"type":"list", "content":["Acquisition program support","Decision analysis and support","Risk analysis and management","Project management and oversight","System lifecycle analysis","System acquisition support","Emerging acquisition methods"]},{"type":"text","content":"DKW’s experience within the Federal acquisition environment has prepared us to support your acquisition needs for systems and for procurements to help defend our nation’s security and safety."}]},
            {"title":"Business Process Reengineering", "state":'app.solutions.managementConsulting({Id: "business-process-reengineering" })',"image":"images/serviceDesk1.jpg", "icon":"fa-briefcase", "content":[{"type":"text", "content":"Business Process Re-engineering (BPR) is a revision of management strategies and process at all organizational levels to improve performance and customer satisfaction while reducing costs. BPR can focus on the entire organization or just one process. It helps organizations rethink how they do their work and how they view the ultimate process outputs to improve customer service. BPR typically involves one or more of these functions: business needs analysis, IT infrastructure analysis, change management for the organization and individuals, and continuous improvement to maintain and improve the effects of re-engineering."}, {"type":"text", "content":"DKW is acutely aware of the value of customer satisfaction. Developing processes that are customer focused is one of our specialties. From mailroom operations to Enterprise Applications development and maintenance, DKW has made some process improvements that increase efficiency and other improvements that are saving our customers millions."}]},
            {"title":"Change Management", "state":'app.solutions.managementConsulting({Id: "change-management" })',"image":"images/serviceDesk1.jpg", "icon":"fa-window-restore", "content":[{"type":"text", "content":"Change Management is a logical outcome of Business Process Re-engineering (BPR). It transforms a process, individual, team, or organization to a defined to-be state. Virtualization, private clouds, globalization, and the incessant innovation of technology result in an evolving business environment that can be a challenge to control. Whether at the micro- (e.g., process) or macro- (e.g., organization) level, the critical success factor is the ability to win buy-in for the change. Effectively managing the change is a four-step process: Understand the change to the business environment; Develop adjustments to organizational and personnel needs; Communicate with and educate the stakeholders and process users about the change; and Win the support of management, stakeholders, users, and process output recipients."}, {"type":"text","content":"DKW has performed BPR and system development and implementation for numerous mission-critical systems: all of which required the buy-in of management, stakeholders, and users. We understand that the road to Change Management success is communication: frequently and at all organizational levels. We are prepared to accept your challenges and foster your success."}]},
            {"title":"Electronic Records Management", "state":'app.solutions.managementConsulting({Id: "electronic-records-management" })',"image":"images/serviceDesk1.jpg", "icon":"fa-table", "content":[{"type":"text", "content":"DKW’s Electronic Records Management team provides the following services on the ERM contract: assists in identifying, addressing, and mitigating the numerous complex issues associated with the lifecycle (creation, use/maintenance, and disposition) management of electronic records (e-records), and makes recommendations for a Records Management Application (RMA), which will be integrated into the current infrastructure with the Document Management application. The team’s IT skill sets and services are needed to manage the ever-increasing inventory of agency e-records, documents, information, email messages, and information systems."},{"type":"pdf-file", "content":{"title":"USAID Records Management Brochure", "location":"downloads/USAID_RecordsManagement.pdf"}}]},
            {"title":"Human Resources", "state":'app.solutions.managementConsulting({Id: "human-resources" })',"image":"images/serviceDesk1.jpg", "icon":"fa-users", "content":[{"type":"text", "content":"DKW Communications, Inc. supports HR with document preparation, indexing, and converting to electronic image a variety of HR program records. We provide Operation and Maintenance (O&M) and technical support in the automation of work processes and back-file conversions of official HR records and information."},{"type":"list", "content":["Document preparation","Indexing","Conversion to electronic image format for a variety of HR records","Operations support", "Back-file conversions","Web-based Electronic Official Personnel Folder (eOPF) management system"]}]},
            {"title":"Information Management", "state":'app.solutions.managementConsulting({Id: "information-management" })',"image":"images/serviceDesk1.jpg", "icon":"fa-info-circle", "content":[{"type":"text", "content":"DKW’s comprehensive life cycle solutions facilitate the management of Federal information and data of mission-critical programs and systems. We’re a professional services company providing IT Operations, Engineering, Program Management, and Administrative services to the U.S. Federal Government. We specialize in the delivery of comprehensive, life cycle support in areas of software engineering; network and telecommunications engineering; network and system operations; records and information management; facilities engineering support; and software and systems development, software maintenance and enhancements, application Help Desk support, software quality assurance, and end-user training using our clients established System Development Lifecycle."}]},
            {"title":"Knowledge Management", "state":'app.solutions.managementConsulting({Id: "knowledge-management" })',"image":"images/serviceDesk1.jpg", "icon":"fa-book", "content":[{"type":"text", "content":"DKW provides system analysis, technology integration and technology implementation support to companies and their products transitioning from development to production. Our subject matter experts offer in-depth knowledge of technologies, tools and processes necessary to achieve feasible solutions that meet performance, cost and schedule objectives. Our services include program plans ranging from system definition to validation."}]},
            {"title":"Program Management", "state":'app.solutions.managementConsulting({Id: "program-management" })',"image":"images/serviceDesk1.jpg", "icon":"fa-tasks", "content":[{"type":"text", "content":"DKW provides system analysis, technology integration and technology implementation support to companies and their products transitioning from development to production. Our subject matter experts offer in-depth knowledge of technologies, tools and processes necessary to achieve feasible solutions that meet performance, cost and schedule objectives. Our services include program plans ranging from system definition to validation."}]}
          ]
        }
      };

    // About Data
    data.ourCompany = {
      "Company|History":{
        "sectionTitle":"Company History",
        "heroText":"OUR HISTORY OF SUCCESS",
        "image":"images/history-hero.jpg", 
        "state":"app.about.companyHistory",
        "content":[{"type":"text", "value":"DKW has an exemplary history of industry recognition for our excellent performance in technical services as well as business management. Since our founding in 2001, we have delivered as a prime on contracts, subcontracts, and task orders and have provided a wide range of Information Security, Information Technology, and Enterprise Solutions for software and systems; Data Communications; Business Process Re-engineering; and Defense Messaging services for our customers in the DC metro area, across the U.S., and abroad."},
           {"type":"text", "value":"We have consistently performed work above and beyond customers’ standards, meeting and exceeding customer expectations. We are committed to delivering the highest quality services and solutions on time and within budget, as attested by our embrace of CMMI, ITIL ISO, EVM, and PMBOK processes as our fundamental way of doing business."},
           {"type":"list", "value":["2008 Inc. 5000 No.873/ ranked No.55 in the Top 100 Government Services Companies & Ranked No.69 in the Top 100 Business in Washington, Arlington, Alexandria","September 2008 Deloitte Technology Fast 50 Rank #12","Deloitte & Touche 2008 Rising Star Technology Award"]},
           {"type":"list", "value":["Washington Technology Fast 50, October 2006 at #2", "MEA Magazine’s Award for Small Business Person of the Year, November 2006", "MEA Magazine’s Award for 100 Fastest Growing Minority Firms, November 2006"]},
           {"type":"list", "value":["2005 Deloitte technology Fast 500 North America Rising Star", "2005 Deloitte Technology Fast 50 Rising Star for Maryland", "Fifty Influential Minorities in Business by Minority Business and Professional Network (6/04)", "Business Person of the Year for Montgomery County by Omega PSI PHI Fraternity (11/03)"]}]
      }
    };

    // News Data
    data.dkwNews = [
        {"date":"", "title":"DKW is now certified as a Local Disadvantaged Business Enterprise", "image":"","content":"DKW is now certified as a Local Disadvantaged Business Enterprise (LDBE) with the Metropolitan Washington Airports Authority (Authority) Expiration Date January 20, 2018"},
        {"date":"", "title":"DKW Selected By the U.S. Marine Corps to Manage Eight Data Centers in San Diego, California", "image":"","content":"DKW was recently awarded a $4.5 million dollar contract with the U.S. Marine Corps to provide network analysis, data center planning, IT project management, network and facilities engineering, and implementation and testing of network designs for eight data centers located in San Diego, California."},
        {"date":"", "title":"DKW Awarded New Contract to Provide IT Support Services to the U.S. Department of Interior", "image":"","content":"The U.S. Department of Interior, Office of Natural Resources Revenue (ONRR) recently selected DKW Communications, Inc. to support its IT operations at its Denver Federal Center in Lakewood, Colorado. ONRR is responsible for the management of revenues associated with Federal offshore and Federal and American Indian onshore mineral leases, as well as revenues received as a result of offshore renewable energy efforts. ONRR also ensures that the nation’s Federal and American Indian natural resources revenues are accurately reported and paid in compliance with laws, regulations, and lease terms. DKW will provide applications development and Documentum support, IT helpdesk support, and database administration."},
        {"date":"", "title":"DKW Awarded $10 Million Dollar Contract to Provide Software Development Services to the United States Department of Agriculture (USDA), Food Safety and Inspection Service", "image":"","content":"The Unites States Department of Agriculture (USDA), Food Safety and Inspection Service (FSIS) selected DKW to provide ongoing software maintenance for its Public Health Information System (PHIS) which supports FSIS in protecting the U.S. food supply by ensuring that our commercial supply of meat, poultry, and egg products is safe, wholesome, and correctly labeled and packaged."}
      ];

    // Contract Vehicles Data
    data.dkwContractVehicles = [
        {"sectionTitle":"Alliant Small Business Governmentwide Acquisition Contract (GWAC)", "content":"This contract vehicle provides a common framework and terminology for defining and understanding the components of an IT solution. Alignment with the FEA and DoDEA enables Alliant Small Business to evolve over time as technologies change without requiring a technical refresh. It also conforms to the Office of Management and Budget (OMB) policy mandates for reporting on IT investments. Low 0.75 percent contract access fee GWACs have the same low fee as GSA Schedules. Access to all types of task orders Alliant Small Business features fixed-price, cost-reimbursement, labor-hour, and time-and-materials task order types, which provide greater flexibility in procuring different types of IT products and services and meeting your mission requirements. How Federal agencies have used Alliant Small Business Operating an information assurance response center One small business was awarded a $52 million task order to operate the Department of Energy’s National Nuclear Security Administration’s (NNSA) Information Assurance Response Center (NIARC) in Las Vegas, NV. Providing IT and cyber support for a CIO’s office The Department of Energy’s National Nuclear Security Administration (NNSA), Office of the Chief Information Officer awarded a $70 million task order to a small business. Encouraging maximum small business utilization in contracting The Department of Defense issued a memo on July 14, 2011, encouraging the use of Alliant Small Business, among other small business GWACs, to meet the Department’s small business contracting and information technology needs. Read the memo (PDF, 145 KB). Increasing competition while reducing acquisition cycle time The Department of the Navy recently conducted a General IT Development and Support Services strategic sourcing analysis, which focused on cost savings. They recommended increasing the use of existing contract vehicles to generate greater competition while reducing cycle time, including the Alliant Small Business GWAC. Alliant Small Business will work with the Navy team to establish and deliver training opportunities. The link to this Web page is www.gsa.gov/alliantsb."},
        {"sectionTitle":"8(a) STARS II Governmentwide Acquisition Contract (GWAC)", "content":"Two constellations based on industry accreditation 8(a) STARS II industry partners are classified in two constellations. Industry partners in both constellations have competitive pricing and technical proficiency. Constellation II also includes industry partners with an additional industry credential, such as Capability Maturity Model Integration (CMMI) or ISO 9001 (quality management system). Access to multiple types of task orders 8(a) STARS II offers fixed price, time and materials, labor hour, and blended task order types, which provides greater flexibility in procuring different types of IT products and services and meeting your mission requirements. How Federal agencies have used 8(a) STARS II Encouraging maximum small business utilization in contracting The Department of Defense issued a memo on July 14, 2011, encouraging the use of 8(a) STARS II, among other small business GWACs, to meet the Department’s small business contracting and IT needs. Read the July 14, 2011 memo (PDF, 146 KB).The link to this Web page is www.gsa.gov/stars2."},
        {"sectionTitle":"OPM IT Services BPA (OPM-32-12-A-0036)", "content":"The Office of Personnel Management (OPM) has issued an IT Services BPA (Blanket Purchase Agreement) to provide the OPM Office of the Chief Information Officer (CIO) with numerous IT services, including network operations and security, data center operations, applications and database software development, Web development, and other support services. The Chief Information Officer, Operations Technology Management, Network Management (NM) supports the OPM mission by managing and operating OPM’s IT infrastructure. This includes the implementation, management, and maintenance of workstations, local and wide area networks (LAN/WAN), data communications, servers, storage area networks (SAN), and IT security initiatives. A BPA is not a contract; rather, it is used by approved agencies to order and pay for supplies and services that they purchase from approved vendors. In the case of the OPM IT Services BPA, the approved vendor is DKW Communications, Inc., the prime contractor on Special Technical Area (STA) 1, which entails Application Systems and Database Development and Maintenance and Special Technical Area (STA) 4, which entails Network and Server Operations and Maintenance, Security Services, Project Management, and Engineering."}
    ];
  }
  return new dkwInfoData();
}]);
